name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./prod-cloud-foundation
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/726010183755/locations/global/workloadIdentityPools/lz-github-pool/providers/lz-provider"
          service_account: "wif-tf-sa@ccoe-seed-project.iam.gserviceaccount.com"
          audience: "https://github.com/sfestic89/cloud-foundation"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve