name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./prod-cloud-foundation
    permissions:
      contents: read
      id-token: write
    
    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      # Let TF wait for transient locks instead of failing fast
      TF_CLI_ARGS_plan: "-lock-timeout=5m"
      TF_CLI_ARGS_apply: "-lock-timeout=5m"
      # Use your billing/quota project to satisfy orgpolicy API quota requirements
      GOOGLE_CLOUD_QUOTA_PROJECT: "ccoe-seed-project"  # <-- set to your quota/billing project ID

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/726010183755/locations/global/workloadIdentityPools/lz-github-pool/providers/lz-provider"
          service_account: "wif-tf-sa@ccoe-seed-project.iam.gserviceaccount.com"
          audience: "https://github.com/sfestic89/cloud-foundation"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve --lock=false
